# Global build settings (optional)
[build]
  command = "echo 'Specify project-specific build commands below'"
  publish = "frontend/landing/build"  # Default publish folder

# Landing page deployment (dermodel.app)
[[context.production]]
  command = "cd frontend/landing && npm install && npm run build"
  publish = "frontend/landing/build"

[[redirects]]
  from = "https://www.dermodel.app/*"
  to = "https://dermodel.app/:splat"
  status = 301
  force = true

# Web app deployment (use.dermodel.app)
[[context."use.dermodel.app"]]
  command = "cd frontend/webapp && npm install && npm run build"
  publish = "frontend/webapp/build"

[[redirects]]
  from = "https://use.dermodel.app/*"
  to = "/index.html"
  status = 200